### ISSUE TITLE
Incomplete repository

### ISSUE THREAD

**Issue by subrtadel** [GreenCUBIC/NICUface#1]
Hello, 

I've noticed that the file "face_orientation_estimation.py" is empty and other python files are missing. Could you please upload them? I would like to run the inference script. 

Thank you in advance
Adela Subrtova

**Comment by ChanAndy** [comment]
I encountered the same issue.

**Comment by jrgreen7** [comment]
@YasminaD has addressed this now. Please let us know if any issues remail.
